### PR TITLE
Resource id and subscription id order fix

### PR DESCRIPTION
**Pull request by Araballi**
Resource id and subscription id value issue is fixed

### CODE REVIEW

**Review by adamchester — CHANGES_REQUESTED** [review]
I think we need a test that verifies we can’t make this same or similar mistake again.

**Comment by adamchester** [comment]
@Araballi I've added a bunch of tests and modified `IConsumptionMetricsDestination` to look like this:

```csharp
public interface IConsumptionMetricsDestination
{
    IConsumptionMetricsDestination ForInternalContext(string propertyName, string value);
    IConsumptionMetricsDestination ForSubscriptionOwnerContext(string propertyName, string value);
    void Write(Guid subscriptionId, Guid resourceId, string meter, int amount, string reason = null);
}
```

I've removed the dependency on 'message templates' and pushed that related logic down to the `Kmd.Logic.Consumption.Client.AuditClient` where it belongs. This makes it easier to test, makes the  interface clearer, and improves our ability to implement it in different ways if necessary in the future.

Please review.

**Comment by Araballi** [comment]
LGTM

**Review by Araballi — COMMENTED** [review]
LGTM

**Review by adamchester — APPROVED** [review]
OK, let's merge this into dev and give a wider test 👍

**Pull request merged**
